sudo: required
dist: trusty
language: generic

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - gcc-5
            - g++-5
          sources:
            - ubuntu-toolchain-r-test

branches:
  except:
    - dev

script:
  - make -C Release all
  - make -C Release test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5c1aeb885d0b7f43a54a
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
