#Tests
TEST_PATH = ../tests/
#ref: http://stackoverflow.com/a/2706067/577298
TEST_FILES = $(wildcard $(TEST_PATH)*.nwt)
TESTS = $(patsubst $(TEST_PATH)%.nwt,%,$(TEST_FILES))

test: newt $(TESTS)

$(TEST_PATH)output:
	mkdir -p $(TEST_PATH)output

%: $(TEST_PATH)%.nwt $(TEST_PATH)output
	-@echo ' '
	./newt --debug $< >$(TEST_PATH)output/$@ 2>&1
	diff $(TEST_PATH)reference/$@ $(TEST_PATH)output/$@

#run a test in debug mode
r%: newt $(TEST_PATH)%.nwt
	-@echo ' '
	./newt --debug $(word 2,$^)

#update the reference output for the given test
w%: newt $(TEST_PATH)%.nwt $(TEST_PATH)reference
	-@echo ' '
	./newt --debug $(word 2,$^) >$(TEST_PATH)reference/$* 2>&1

c%: $(TEST_PATH)%.nwt
	@cat -n $<

#compare test w/ reference output (requires kdiff)
d%: $(TEST_PATH)%.nwt $(TEST_PATH)reference
	kdiff3 $(TEST_PATH)reference/$* $(TEST_PATH)output/$* 

test-clean:
	rm -rf $(TEST_PATH)output/*
